config/routes.rb
RamusVykaz::Application.routes.draw do
  resources :asistents

  resources :osobas

  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root 'asistents#index'

end

app/models/asistent.rb
class Asistent < ActiveRecord::Base
end

app/models/osoba.rb
class Osoba < ActiveRecord::Base
  has_many :prace_polozkas
end

app/models/prace_polozka.rb
class PracePolozka < ActiveRecord::Base
  belongs_to :osoba
  belongs_to :projekt
  accepts_nested_attributes_for :osoba, :allow_destroy => true, :reject_if => proc { |obj| obj.blank? }
  accepts_nested_attributes_for :projekt, :allow_destroy => true, :reject_if => proc { |obj| obj.blank? }
  validates :hodiny, :numericality => { :greater_than_or_equal_to => 0}
end

app/models/projekt.rb
class Projekt < ActiveRecord::Base
  has_many :prace_polozkas
  end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  # validates :osoba_id, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/asistents_controller.rb
class AsistentsController < ApplicationController
  before_action :set_asistent, only: [:show, :edit, :update, :destroy]

  # GET /asistents
  # GET /asistents.json
  def index
    @asistents = Asistent.all
  end

  # GET /asistents/1
  # GET /asistents/1.json
  def show
  end

  # GET /asistents/new
  def new
    @asistent = Asistent.new
  end

  # GET /asistents/1/edit
  def edit
  end

  # POST /asistents
  # POST /asistents.json
  def create
    @asistent = Asistent.new(asistent_params)

    respond_to do |format|
      if @asistent.save
        format.html { redirect_to @asistent, notice: 'Asistent was successfully created.' }
        format.json { render action: 'show', status: :created, location: @asistent }
      else
        format.html { render action: 'new' }
        format.json { render json: @asistent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asistents/1
  # PATCH/PUT /asistents/1.json
  def update
    respond_to do |format|
      if @asistent.update(asistent_params)
        format.html { redirect_to @asistent, notice: 'Asistent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @asistent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asistents/1
  # DELETE /asistents/1.json
  def destroy
    @asistent.destroy
    respond_to do |format|
      format.html { redirect_to asistents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asistent
      @asistent = Asistent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asistent_params
      params.require(:asistent).permit(:jmeno, :prijmeni, :email, :telefon)
    end
end

app/controllers/osobas_controller.rb
class OsobasController < ApplicationController
end

app/controllers/prace_polozkas_controller.rb
class PracePolozkasController < ApplicationController
  before_action :set_prace_polozka, only: [:show, :edit, :update, :destroy]
  # GET /prace_polozkas
  # GET /prace_polozkas.json
  def index
    @prace_polozkas = PracePolozka.all
    if signed_in?
      @aktualni_hodiny = PracePolozka.where(osoba_id: current_user.osoba_id).sum('hodiny')
    end
  end

  # GET /prace_polozkas/1
  # GET /prace_polozkas/1.json
  def show
  end

  # GET /prace_polozkas/new
  def new
    @prace_polozka = PracePolozka.new
    projektsort
  end

  # GET /prace_polozkas/1/edit
  def edit
    projektsort
  end

  # POST /prace_polozkas
  # POST /prace_polozkas.json
  def create
    @prace_polozka = PracePolozka.new(prace_polozka_params)

    respond_to do |format|
      if @prace_polozka.save
        format.html { redirect_to @prace_polozka, notice: 'Zaznam byl vytvoren.' }
        format.json { render action: 'show', status: :created, location: @prace_polozka }
      else
        format.html { render action: 'new' }
        format.json { render json: @prace_polozka.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prace_polozkas/1
  # PATCH/PUT /prace_polozkas/1.json
  def update
    respond_to do |format|
      if @prace_polozka.update(prace_polozka_params)
        format.html { redirect_to @prace_polozka, notice: 'Zaznam byl zmenen.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prace_polozka.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prace_polozkas/1
  # DELETE /prace_polozkas/1.json
  def destroy
    @prace_polozka.destroy
    respond_to do |format|
      format.html { redirect_to prace_polozkas_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_prace_polozka
    @prace_polozka = PracePolozka.find(params[:id])
  end
  
  def projektsort
    @projekts = Projekt.all.collect {|p| [p.nazev, p.id]}.sort
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def prace_polozka_params
    params.require(:prace_polozka).permit(:osoba_id, :projekt_id, :datum, :obsah, :hodiny)
  end
end

app/controllers/projekts_controller.rb
class ProjektsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_url
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
        sign_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asistents_helper.rb
module AsistentsHelper
end

app/helpers/osobas_helper.rb
module OsobasHelper
end

app/helpers/prace_polozkas_helper.rb
module PracePolozkasHelper
end

app/helpers/projekts_helper.rb
module ProjektsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
    User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/asistents/_form.html.erb
<%= form_for(@asistent) do |f| %>
  <% if @asistent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asistent.errors.count, "error") %> prohibited this asistent from being saved:</h2>

      <ul>
      <% @asistent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :jmeno %><br>
    <%= f.text_field :jmeno %>
  </div>
  <div class="field">
    <%= f.label :prijmeni %><br>
    <%= f.text_field :prijmeni %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefon %><br>
    <%= f.number_field :telefon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asistents/edit.html.erb
<h1>Editing asistent</h1>

<%= render 'form' %>

<%= link_to 'Show', @asistent %> |
<%= link_to 'Back', asistents_path %>

app/views/asistents/index.html.erb
<div class="padding">
	<div class="panel panel-default">
		<div class="panel-body center">

			<% if signed_in? %>
				<% if current_user.email != "asistent@ramus.je" %>
				<%= link_to 'Vlozit asistenta', new_asistent_path %>
				<% end %>
			<table id="asistents" class="table table-condensed table-hover table-bordered">
				<thead>
					<tr>
						<th>Jméno</th>
						<th>Příjmení</th>
						<th>Email</th>
						<th>Telefon</th>
					<% if current_user.email != "asistent@ramus.je" %>	
						<th></th>
						<th></th>
					<% end %>
					</tr>
				</thead>

				<tbody>
					<% @asistents.each do |asistent| %>
					<tr>
						<td><%= asistent.jmeno %></td>
						<td><%= asistent.prijmeni %></td>
						<td><%= asistent.email %></td>
						<td><%= asistent.telefon %></td>
					  <% if current_user.email != "asistent@ramus.je" %>
			            <td>
			              <%= link_to 'Upravit záznam', edit_asistent_path(asistent) %>
			            </td>
					    <td>
			              <%= link_to 'Smazat záznam', asistent, method: :delete, data: { confirm: 'Rozmysli si, Maruško, rozmysli!' } %>
			            </td>
				      <% end %>
			        </tr>
					<% end %>

				</tbody>
				<tfoot>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					  <% if current_user.email != "asistent@ramus.je" %>
			            <td></td>
			            <td></td>
				      <% end %>
					</tr>
				</tfoot>
			</table>

<% else %>
			<div class="container">
				<div class="row">
          			<h1 class="nazev">KONTAKTNÍK<br>RAMUSISTENTŮ</h1>
					<%= link_to "přihlaš se!", signin_path, :class => "btn btn-lg btn-prihlas" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/asistents/new.html.erb
<h1>New asistent</h1>

<%= render 'form' %>

<%= link_to 'Back', asistents_path %>

app/views/asistents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jmeno:</strong>
  <%= @asistent.jmeno %>
</p>

<p>
  <strong>Prijmeni:</strong>
  <%= @asistent.prijmeni %>
</p>

<p>
  <strong>Email:</strong>
  <%= @asistent.email %>
</p>

<p>
  <strong>Telefon:</strong>
  <%= @asistent.telefon %>
</p>

<%= link_to 'Edit', edit_asistent_path(@asistent) %> |
<%= link_to 'Back', asistents_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "KONTAKTNÍK RAMUSISTENTŮ", root_path, class: 'h1 navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<%= render 'layouts/navigation_links' %>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if signed_in? %>
				<li class="navbar-text">
					<% if current_user.email == "asistent@ramus.je" %>
						<%= 'jsi přihlášen/a jako ASISTENT' %>
					<% else %>
					<%= 'jsi přihlášen/a jako ADMINISTRÁTOR: '%>
					<%= Osoba.find_by(id: current_user.osoba_id).jmeno + " " +
					Osoba.find_by(id: current_user.osoba_id).prijmeni %>
					<% end %>
				</li>
				<li class="navbar-text">|</li>
				<li>
					<%= link_to "odhlaš se!", signout_path, method: "delete", :class => "" %>
				</li>

				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Ramus // Kontaktník ramusistentů" %></title>
		<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Kontaktník ramusistentů" %>">
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header>
			<%= render 'layouts/navigation' %>
		</header>
		<main role="main">
			<%= render 'layouts/messages' %>
			<%= yield %>
		</main>
	</body>
	<div class="container">
	<footer class="row">
		<section class="col-md-6">Kopyrajt Ramus ajtý sekce</section>
		<section class="col-md-6">Made during a lunch break</section>
	</footer>
	</div>
</html>

app/views/prace_polozkas/_form.html.erb
<%= form_for(@prace_polozka) do |f| %>
<% if @prace_polozka.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@prace_polozka.errors.count, "error") %> prohibited this prace_polozka from being saved:</h2>

	<ul>
		<% @prace_polozka.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.hidden_field :osoba_id, :value => current_user.osoba_id %>
</div>
<div class="field">
	<%= f.label :projekt_id %>
	<br>
	<%= f.select(:projekt_id, @projekts) %>
</div>
<div class="field">
	<%= f.label :datum %>
	<br>
	<%= f.text_field(:datum , :behaviour => 'datepicker', :value => @prace_polozka.datum.blank? ? Date.today : @prace_polozka.datum) %>
</div>
<div class="field">
	<%= f.label :obsah %>
	<br>
	<%= f.text_area :obsah %>
</div>
<div class="field">
	<%= f.label :hodiny %>
	<br>
	<%= f.number_field :hodiny, :step => "0.25",:min => "0" %>
</div>
<div class="actions">
	<%= f.submit 'Uložit' %>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('[behaviour~=datepicker]').datepicker({
			format : "dd.mm.yyyy",
			weekStart : 1,
			todayBtn : "linked",
			language : "cs",
			todayHighlight : true
		}
		);
	})

</script>

<% end %>

app/views/prace_polozkas/edit.html.erb
<%= render 'form' %>

<%= link_to 'K výkazu práce', prace_polozkas_path %>

app/views/prace_polozkas/index.html.erb
<div id="novyzapisbtn">
  <% if signed_in? %>
    <%= link_to 'zapsat novou práci?', new_prace_polozka_path, :class => "kontrastbtn" %>
  <% end %>
</div>

<div class="padding">
	<div class="panel panel-default">
		<div class="panel-body center">

			<% if signed_in? %>
			<table id="prace_polozkas" class="table table-condensed table-hover table-bordered">
				<thead>
					<tr>
						<th>Datum</th>
						<th>Jméno</th>
						<th>Práce pro projekt</th>
						<th>Náplň práce</th>
						<th>Počet hodin</th>
						<th></th>
						<th class="cellaccent"></th>
					</tr>
				</thead>

				<tbody>
					<% @prace_polozkas.each do |prace_polozka| %>
					<tr>
						<td><%= prace_polozka.datum %></td>
						<td><%= Osoba.find_by(id: prace_polozka.osoba_id).jmeno + " " + Osoba.find_by(id: prace_polozka.osoba_id).prijmeni %></td>
						<td><%= Projekt.find_by(id: prace_polozka.projekt_id).nazev %></td>
						<td><%= prace_polozka.obsah %></td>
						<td><%= prace_polozka.hodiny %></td>
                        
						<td>
              <% if current_user.osoba_id == 8 or current_user.osoba_id == Osoba.find_by(id: prace_polozka.osoba_id).id  %>
              <%= link_to 'Upravit záznam', edit_prace_polozka_path(prace_polozka) %>
              <% end %>
            </td>
						            
            <td>
              <% if current_user.osoba_id == 8 or current_user.osoba_id == Osoba.find_by(id: prace_polozka.osoba_id).id  %>
              <%= link_to 'Smazat záznam', prace_polozka, method: :delete, data: { confirm: 'Rozmysli si, Maruško, rozmysli!' } %></td>
				      <% end %>
          </tr>
					<% end %>

				</tbody>
				<tfoot>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tfoot>
			</table>

			<div class="container">
				<div class="row">
          <% else %>
					<%= link_to "přihlaš se!", signin_path, :class => "btn btn-lg btn-warning" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/prace_polozkas/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', prace_polozkas_path %>

app/views/prace_polozkas/show.html.erb
<p id="notice"></p>

<p>
  <strong>Osoba:</strong>
  <%= @prace_polozka.osoba_id %>
</p>

<p>
  <strong>Projekt:</strong>
  <%= @prace_polozka.projekt_id %>
</p>

<p>
  <strong>Datum:</strong>
  <%= @prace_polozka.datum %>
</p>

<p>
  <strong>Obsah:</strong>
  <%= @prace_polozka.obsah %>
</p>

<p>
  <strong>Hodiny:</strong>
  <%= @prace_polozka.hodiny %>
</p>

<%= link_to 'Upravit záznam', edit_prace_polozka_path(@prace_polozka) %> |
<%= link_to 'K výkazu práce', prace_polozkas_path %>